Add Library Book Return preset
openstreetmap/id-tagging-schema pull request #1037
Opened 2023-10-28 02:54 UTC by arch0345

Adds a preset for [`amenity=library_dropoff`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlibrary_dropoff) which was approved back in 2022

2023-11-23 04:27 UTC, matkoniecz requested changes
"Library Book Return" sounds like including desk at library where books are normally returned, while https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlibrary_dropoff defines it as "A remote dropoff location for a library."

2023-11-27 17:16 UTC, tyrasd approved these changes

2023-11-27 17:29 UTC, tyrasd commented
I think @matkoniecz has a valid point here. While _library [book returns](https://americansecuritycabinets.com/products/book-returns/)_ seems to be the correct term for these drop boxes, there could be confusion with _in person_ book returns ([example usage](https://www.lib.cam.ac.uk/using-library/zero-contact-services/book-returns)). But I think the adjective _remote_ could also be irritating, because these devices are often found just outside or even inside of a particular library building.

Would something like _Book Returns Drop Box_ potentially work, @arch0345 ?

2024-02-05 13:57 UTC, tyrasd approved these changes

2024-02-05 13:57 UTC, merged