Regional Preset: highway=path for foot+bicycle in Israel
openstreetmap/id-tagging-schema pull request #1062
Opened 2023-11-23 12:05 UTC by zstadler

In #1058 the Israel was excluded from the system default of using `highway=cycleway` for "foot+bicycle" paths.

The goal of this PR is to create an Israel-specific preset of using `highway=path` for "foot+bicycle" paths.

It is based on the [global presets](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/cycleway/bicycle_foot.json) and adds [MTB](https://wiki.openstreetmap.org/wiki/Mountain_biking)-related tags which are recommended in Israel.

Please let me know if additional files are needed as part of this PR.

2023-11-26 12:45 UTC, westnordost commented
Regional presets are a really bad idea. See https://github.com/ideditor/schema-builder/issues/94

2024-07-06 13:00 UTC, tordans commented
I might be missing something here … but we could just add the mtp fields as moreFields on the existing present, right? 

Or, if that is not ideal, that add the fields there but move the regional filter to the field, like it was done in https://github.com/openstreetmap/id-tagging-schema/commit/ae68feef3c3d8fc99de1b894f109a2ee34fee7a8 which is related to the linked issue.

2024-07-06 13:01 UTC, tordans requested changes
This just adds a formal PR status (see previous comment).

2024-12-01 23:47 UTC, hlfan commented
#1384 is presumably the better version for this tagging variant.

2026-07-23 13:55 UTC, matkoniecz commented on data/presets/highway/path/bicycle_foot-IL.json
> +    "name": "Cycle & Foot Path"
this should reference another preset, to not add work for translators 

see https://github.com/openstreetmap/id-tagging-schema/blob/main/SCHEMA.md#name for syntax

2026-07-23 14:01 UTC, matkoniecz requested changes
I still have no idea what to do about this one and Norway one but from technical side:

likely crossing ways presets also should be modified, likely existing preset should be excluded from this areas, hidden one for `highway=cycleway` based should be added so existing valid data is not shown in confusing way...

See https://github.com/openstreetmap/id-tagging-schema/pull/1792/changes

I do not expect any work to be done while iD maintainers hesitate on acceptance or rejection of general concept of having managerie of local presets for preferred cycle path tagging

it is quite annoying, both from perspective of community having preferences, data consumers faced with random differences for tagging the same thing and nightmare fragmentation of bajillion crossing presets

I myself do not understand how crossing presets work, and adding multitude of regional variations would make it worse

2026-07-23 14:01 UTC, matkoniecz commented on data/fields/oneway/mtb.json
> +{
if this makes sense it should be added to global one

2026-07-23 14:02 UTC, matkoniecz commented on data/fields/mtb/name.json
> +    "key": "mtb:name",
if this makes sense it should be added to global one

please remove it from this PR (and please remove it if it is not abandoned, this should be simple enough to not be too annoying and is definitely a blocker for a merge)

2026-07-23 14:03 UTC, matkoniecz commented on data/presets/highway/path/bicycle_foot-IL.json
> +        "mtb/name",
field list should reference global preset (feel free to wait with this until general fate of PR is decided)

2026-07-23 14:04 UTC, matkoniecz commented on data/presets/highway/path/bicycle_foot-IL.json
> +        "mtb/name",
see how https://github.com/openstreetmap/id-tagging-schema/pull/1792/changes references field lists

2026-07-23 14:05 UTC, matkoniecz commented on data/fields/oneway/mtb.json
> +{
please remove it from this PR (and please remove it if it is not abandoned, this should be simple enough to not be too annoying and is definitely a blocker for a merge)

2026-07-23 14:06 UTC, matkoniecz commented on data/fields/oneway/mtb.json
> +{
note that it was already noted in https://github.com/openstreetmap/id-tagging-schema/pull/1062#issuecomment-2211763247

2026-07-23 14:06 UTC, matkoniecz commented on data/fields/mtb/name.json
> +    "key": "mtb:name",
note that it was already noted in https://github.com/openstreetmap/id-tagging-schema/pull/1062#issuecomment-2211763247

2026-08-04 11:35 UTC, matkoniecz commented on data/fields/mtb/name.json
> +    "key": "mtb:name",
@zstadler note that if it is an abandoned PR it will be closed as rejected

2026-08-04 11:58 UTC, zstadler commented on data/fields/mtb/name.json
> +    "key": "mtb:name",
@matkoniecz wrote:
> if this makes sense it should be added to global one

I'm not in a position have an opinion if this makes sense or how it could be added to global one. Please be clear to who this question is directed.

2026-08-04 11:58 UTC, zstadler commented on data/fields/mtb/name.json
> +    "key": "mtb:name",
This PR was ready on Nov 23, 2023 and planned for merge right after

> <img width="584" height="235" alt="image" src="https://github.com/user-attachments/assets/6d257b9c-9bf5-487b-9dd0-b8b31a144940" />

Please note that
> The goal of this PR is to create an Israel-specific preset of using highway=path for "foot+bicycle" paths.

I really don't mind how that goal is achieved. The repository maintainers, including those who have suggested alternative implementation paths, were given permission to edit this PR from day one.

> <img width="274" height="156" alt="image" src="https://github.com/user-attachments/assets/f9940f18-0c02-4a20-bb77-a6141ac5d5f8" />

If the PR is rejected, I'll be happy to open a new issue for the problem.

2026-08-04 12:08 UTC, k-yle requested changes
this was already merged in #1384 - so we just need to add `IL`/`PS` to those files, right?

2026-08-04 12:10 UTC, matkoniecz commented
I see IL and PS already in https://github.com/openstreetmap/id-tagging-schema/pull/1384/changes

2026-08-05 08:49 UTC, k-yle commented
> If the PR is rejected, I'll be happy to open a new issue for the problem.

@zstadler you wrote that [yesterday](https://github.com/openstreetmap/id-tagging-schema/pull/1062#discussion_r3712158872), but this change was released [nearly 2 years ago](https://github.com/openstreetmap/id-tagging-schema/pull/1384#event-15728556258) for israel...

if you're referring to the `oneway:mtb` tags, please open a new issue or PR for that. Since that tag is undocumented and originated from a single import in israel, it is likely that maintainers will have further comments, and that discussion should happen in a dedicated issue

2026-08-05 08:49 UTC, closed without merging

2026-08-05 09:25 UTC, matkoniecz commented
> Since that tag is undocumented and originated from a single import in israel

I would treat it as a strong indicator that it is a tag without wider consensus

2026-08-05 09:26 UTC, matkoniecz commented
> @zstadler you wrote that https://github.com/openstreetmap/id-tagging-schema/pull/1062#discussion_r3712158872, but this change was released https://github.com/openstreetmap/id-tagging-schema/pull/1384#event-15728556258 for israel...

so if you would open a new issue you would need to be clear what is supposed to be changed from the current state

2026-08-05 10:46 UTC, zstadler commented
@k-yle 
> > @zstadler you wrote that [#1062 (comment)](https://github.com/openstreetmap/id-tagging-schema/pull/1062#discussion_r3712158872), but this change was released [#1384 (comment)](https://github.com/openstreetmap/id-tagging-schema/pull/1384#event-15728556258) for israel...
> 
> so if you would open a new issue you would need to be clear what is supposed to be changed from the current state

I'm sorry for not following every commit in this repository. In Nov 2023 I was merely asking that iD will be adapted for the tagging conventions in Israel. Foolishly, I've also tried to implement it in the best way I understood and using the conventions I've seen in the code at that time.

I was not the one who merged  [#1384 (comment)](https://github.com/openstreetmap/id-tagging-schema/pull/1384#event-15728556258) in Nov 2024 without closing this PR or marking it as a duplicate, despite having [this](https://github.com/openstreetmap/id-tagging-schema/pull/1062#issuecomment-2510310309) cross referencing the two PRs.

It looks like #1384 was such a well-kept secret that the discussion on this PR was revived in July 2026 without anyone realizing that its goal has already been resolved almost 2 years ago...

2026-08-05 10:55 UTC, matkoniecz commented
well, either way it is resolved now, right?

2026-08-05 13:14 UTC, zstadler commented
Yes, it looks like it is resolved.