Add `cross` term to `historic = wayside_cross` preset
openstreetmap/id-tagging-schema pull request #1181
Opened 2024-03-28 09:48 UTC by FloEdelmann

In German, "Wayside Cross" is translated to "Wegkreuz", so the preset is not findable with the query "Kreuz". Adding a translatable term "cross" would mitigate that. See https://github.com/streetcomplete/StreetComplete/issues/5557.

2024-03-28 09:56 UTC, tordans commented
Is "Wegkreuz", "Kreuz" part of the German translations already?

2024-03-28 11:07 UTC, rugk requested changes

2024-03-28 11:07 UTC, rugk commented on data/presets/historic/wayside_cross.json
> +        "cross"
```suggestion
        "cross", 
        "Christian", 
        "Jesus", 
        "Christ"
```

These should alow be added as indicated in the issue? As at least in Germany it's usually a Jesus statue being at the cross.

2024-03-28 11:14 UTC, tordans commented
German translations belong in the translation system, not the repo, see https://github.com/openstreetmap/id-tagging-schema/blob/main/CONTRIBUTING.md#translating for more. Short version: Only EN is part of the repo, all other languages are managed in the translations system. The repo should only have EN (with very few exceptions if any for country specific presets/fields).

2024-03-28 11:35 UTC, FloEdelmann commented
But the terms I added are not German or German-specific. They are added in English and should be translated to all languages via Transifex. Do you disagree with that, or did I miss something?

2024-04-05 15:50 UTC, tyrasd commented
I changed [Christus](https://dict.leo.org/englisch-deutsch/Christus) to Christ. lgtm

2024-04-05 15:59 UTC, merged