defibrillator.json: Added check_date to fields
openstreetmap/id-tagging-schema pull request #1184
Opened 2024-03-29 20:54 UTC by jpds

This is used by consumers such as OpenAEDMap.

2024-04-05 15:01 UTC, tyrasd commented
The `check_date` field has the `"universal": true` flag, and is therefore already available for all presets. This change would only affect AED features which do not have this tag already (then the universal field is "hidden" under "more fields"). Was is the intent of this PR to make it visible also if unset?

I'm just wondering why this preset should be handled differently compared to other features, like other emergency infrastructure like fire hydrants for example.

2024-04-06 20:30 UTC, jpds commented
> Was is the intent of this PR to make it visible also if unset?

Yes, I hadn't thought about the other emergency things - do I just move it into `_emergency.json` ?

2024-04-10 14:30 UTC, tyrasd commented
good idea. let's try adding it to the generic `_emergency.json` preset

2025-12-16 05:12 UTC, matkoniecz approved these changes

2025-12-16 05:18 UTC, matkoniecz requested changes
on testing it does not actually seem to change things?

if AED is not tagged with check date (see say https://www.openstreetmap.org/edit?editor=id#map=24/50.02552718/19.90116060 ) it can be added as extra field but is not shown by default

I the same behavior after this change, and while AED with check date tagged already will show its field the same applies now, see https://pr-1184--ideditor-presets-preview.netlify.app/id/dist/#locale=en&disable_features=boundaries&map=21.87/50.06995/20.04129&background=Bing&id=n12141941802

what exactly is expected to be changed by this PR?

2026-01-02 11:11 UTC, matkoniecz commented
what exactly is expected to be changed by this PR?

can anyone point out how behaviour changes compared to current iD behaviour? Or is it influencing other editors?

2026-01-02 11:51 UTC, jpds commented
This was so long ago, but the whole point was to display the check date on these entries by default so that users would fill it in.

2026-01-02 12:06 UTC, matkoniecz commented
when I tested in on AED it was still not shown by default if it was empty
<img width="396" height="854" alt="screen-2026-01-02-13-07-08" src="https://github.com/user-attachments/assets/d1ddb925-ff85-4910-a947-2203fb562fdd" />

2026-01-15 18:56 UTC, matkoniecz commented
Is it working for you?

2026-03-05 05:46 UTC, matkoniecz commented
@jpds ping?

2026-04-18 03:39 UTC, matkoniecz commented
Closing as abandoned and not actually working

2026-04-18 03:39 UTC, closed without merging