Add preset for `mountain_pass=yes`
openstreetmap/id-tagging-schema pull request #1224
Opened 2024-05-14 16:55 UTC by playerEric1

Solves issue [#541](https://github.com/openstreetmap/id-tagging-schema/issues/541)

2024-05-15 05:33 UTC, tordans commented
Could you also share screenshots of the info (I) text in the preview so we ca see what the Wikidata item returns as a help text. I think that text will be important to distinguish the two presets. You might have to add or modify the Wikidata item. On the OSM wiki.

2024-06-05 19:19 UTC, Dimitar5555 commented
node/2661769073

![image](https://github.com/openstreetmap/id-tagging-schema/assets/19364673/638fc2f6-8b47-4c46-9207-a257848683e0)

2024-06-05 19:26 UTC, tordans requested changes
Let's first discuss https://github.com/openstreetmap/id-tagging-schema/issues/541#issuecomment-2150797475

2024-07-22 17:01 UTC, tyrasd commented on data/presets/mountain_pass.json
> +        "point",
```suggestion
```

I've only seen `mountain_pass=yes` mapped as a vertex. If there's no road (or path) going through, a saddle is just a saddle, isn't it?

2025-09-08 07:23 UTC, matkoniecz commented on data/presets/mountain_pass.json
> +        "point",
@playerEric1 ping

2025-12-15 16:31 UTC, matkoniecz commented on data/presets/mountain_pass.json
> +        "point",
@playerEric1 ping

is this PR abandoned? If yes, then I plan to close as abandoned it in about 150 days.

2026-07-02 04:36 UTC, matkoniecz commented
closing per https://github.com/openstreetmap/id-tagging-schema/pull/1224/changes#r2620079870

2026-07-02 04:36 UTC, closed without merging