Add leisure=schoolyard
openstreetmap/id-tagging-schema pull request #134
Opened 2021-02-20 22:47 UTC by TurnrDev

Add schoolyard preset based on wiki page for leisure=schoolyard. 

Icon might need changing but I don't know

2021-05-27 21:43 UTC, TurnrDev commented
Is this repo maintained?

2021-05-28 05:13 UTC, tordans commented
I think not, as it is part of the ID ecosystem. 

https://blog.openstreetmap.org/2021/04/26/joint-statement-from-quincy-morgan-and-the-osmf-board/

https://twitter.com/quincylvania/status/1387072971773206533?s=21

https://twitter.com/osm_tech/status/1389546368197349376?s=21

2021-05-28 05:32 UTC, bryceco commented
It’s not abandoned, it’s just waiting for Quincy’s replacement to come along. Or somebody could adopt it. But nothing here will be available to iD until iD has a new maintainer so there’s no hurry to merge here.

2021-05-28 07:07 UTC, TurnrDev commented
> https://twitter.com/osm_tech/status/1389546368197349376?s=21

Ah shame, if I had a better knowledge of JavaScript I would have applied to the position.

2021-05-28 13:28 UTC, bhousel commented
> It’s not abandoned, it’s just waiting for Quincy’s replacement to come along. Or somebody could adopt it. But nothing here will be available to iD until iD has a new maintainer so there’s no hurry to merge here.

Projects shouldn't really depend on a single person to be the maintainer.  Is anyone from the openstreetmap org willing to work with me to transfer this repo over to either the osmlab or ideditor organization so that the community can maintain it?   I could just move the code, but it's nicer to have the whole repo transferred so we can keep the issues and history.

2021-11-10 15:03 UTC, mbrzakovic submitted a review, later dismissed
I don't see much traction on the usage of this tag, however [wiki ](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dschoolyard) clearly states that this tagging is appropriate for mapping schoolyards and [this comment](https://github.com/gravitystorm/openstreetmap-carto/issues/4324#issuecomment-778519405) does have a good point,

2021-11-10 17:58 UTC, 1ec5 commented on data/presets/leisure/schoolyard.json
> +        "school playground",
By the way, this is also known as a “blacktop” in American English (even when the asphalt pavement has faded to a light gray) to distinguish from the other meaning of “schoolyard” that refers to the whole grounds.

2021-12-14 17:59 UTC, tyrasd requested changes, later dismissed
While the usage of this tag has increased quite a bit over the past year or so, it still is orders of magnitudes lower than what would expect from a really well established tag. Given the the tag also didn't undergo a proposal stage as far as I can see, I think its best to not yet merge this at the moment.

Also, the playground icon is really not ideal, since the schoolyard is supposed to be a mapped alongside a school's actual playground.

2021-12-16 03:27 UTC, 1ec5 commented
> it still is orders of magnitudes lower than what would expect from a really well established tag

“Orders of magnitude”, plural, might be overstating it a bit. 🙂 It’s pretty unlikely that the community will ever find the same order of magnitude of schoolyards as playgrounds (which are two orders of magnitude more common in the database). A correctly micromapped schoolground might have just one `leisure=schoolyard` but a dozen `leisure=playground`s corresponding to the mulched area around each playground set.

> Also, the playground icon is really not ideal, since the schoolyard is supposed to be a mapped alongside a school's actual playground.

Agreed, the existing swing icon would be misleading for this preset. I’m unsure what would be a better preset though. These things are characterized by being quite plain, often little more than a big paved area. Maybe something like the existing Pedestrian Area icon, but with a figure of a running child inside instead of a generic walking person? Or playing with a jumprope (skipping rope)?

2021-12-16 17:27 UTC, tyrasd commented
I was [comparing it](https://taghistory.raifer.tech/#***/leisure/schoolyard&***/building/school) to `building=school`, which one could consider to be around at the same micromapping-level (going with the example diagram given in the wiki for `leisure=schoolyard`), and I assumed that most schools in reality consist of a similar number yards as of buildings. But perhaps its that's a bit "unfair" to the poor non-building tag. :wink:

The main problem I have with accepting this relatively new tag (again, compared to its school related map feature siblings) is that it didn't undergo a proposal stage is that it could always be the case that it turns out to be "problematic". Maybe the `leisure` is suboptimal, and something like `landuse=schoolyard` would have been the better choice. Or maybe these places would be better mapped as a special kind of playground (e.g. `leisure=playground` + `playground=schoolyard`) or even as a pedestrian area (thinking about it… something like `highway=pedestrian` + `area=yes` + `pedestrian=schoolyard` + `access=…` would even work to bad from a routing point of view). I just don't know. :shrug: 

FWIW, JOSM also doesn't have a preset for `leisure=schoolyard` at the moment.

2024-02-07 11:02 UTC, TurnrDev commented on data/presets/leisure/schoolyard.json
> +        "school playground",
```suggestion
        "blacktop",
        "school playground",
```

2024-08-07 11:12 UTC, matkoniecz commented
> The main problem I have with accepting this relatively new tag (again, compared to its school related map feature siblings) is that it didn't undergo a proposal stage is that it could always be the case that it turns out to be "problematic". Maybe the leisure is suboptimal, and something like landuse=schoolyard would have been the better choice. Or maybe these places would be better mapped as a special kind of playground (e.g. leisure=playground + playground=schoolyard) or even as a pedestrian area (thinking about it… something like highway=pedestrian + area=yes + pedestrian=schoolyard + access=… would even work to bad from a routing point of view). I just don't know. 🤷

I think it is perfectly fine for this tag to be far less used, it is kind of micromapping - in the same way as typical school will not have footway going to mapped or trees next to it will not be mapped

what you think about making a thread at community forums to check is there any real opposition to this tag or concerns? And accept is as valid if there are no real complaints

2024-08-08 15:43 UTC, tyrasd commented
> what you think about making a thread at community forums to check is there any real opposition to this tag or concerns? And accept is as valid if there are no real complaints

Something like a forum thread would be the minimum to be expected for a tag that's meant to be used in the micromapping of a thing as prominent as schools.

See also our new [general guidelines](https://github.com/openstreetmap/id-tagging-schema/blob/main/GUIDELINES.md#general-guidelines).

@TurnrDev I know it has been a long time since you opened this PR. Are you still interested in bringing this effort forward? If yes, it would be very much appreciated if you could start a discussion about this and after a suitable time report back here with a summary. :pray:

2024-08-08 15:49 UTC, TurnrDev commented
I appreciate I was the one who initially created this PR, and thus it makes sense for me to lead that discussion, however, leading discussions is not really one of my strengths and my investment to this is not that high. (I'm always that person with the mic off and camera off in any meeting above 3 people.) I'm going to kindly decline, but with that said, I'm going to leave the PR open and am happy to make any changes necessary if someone else does pick up that discussion.

2024-08-08 15:55 UTC, matkoniecz commented
hmm, I think I can create thread like this om community forums:

title: leisure=schoolyard - is it a good tag worth promoting?

body: 

There is https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dschoolyard tag that seems reasonable to me. But, partially because it is kind of micromapping it is used relatively rarely. 

At https://github.com/openstreetmap/id-tagging-schema/pull/134 it was proposed to add it to presets but maintainers are worried that there are some possible problems with it as it is relatively rare and have not went through proposal process.

Are you aware about any issues with this tag that should result in it not being promoted by presets? Or is it a fine tag worth supporting for example in iD presets?

2024-08-08 16:14 UTC, tyrasd commented
@TurnrDev fair enough. That's totally ok. 

@matkoniecz thanks for the offer to take this over! :+1:  If you want, you can quote my concerns from my comment above: https://github.com/openstreetmap/id-tagging-schema/pull/134#issuecomment-996027141

2024-08-08 17:36 UTC, matkoniecz commented
posted on https://community.openstreetmap.org/t/leisure-schoolyard-is-it-a-good-tag-worth-promoting/117170

2024-12-03 09:02 UTC, TurnrDev commented
Seems the overall consensus on your post if positive - how long do we usually leave these things? @matkoniecz

2024-12-03 09:17 UTC, matkoniecz commented
I would say that anyone who wanted to comment probably did and there is no point in waiting more for comments.

I have somewhere on my todo list to go through comments/reactions and check what is the general sentiment and whether any serious issues were raised.

2025-09-23 12:18 UTC, matkoniecz commented
I marked multiple discussion sections at https://wiki.openstreetmap.org/wiki/Talk:Tag:leisure%3Dschoolyard as resolved

2025-11-23 06:23 UTC, matkoniecz commented
Now all sections on wiki are resolved

2026-03-03 00:48 UTC, matkoniecz commented
@TurnrDev I merged in master myself, as I have not wanted to bother you about over 5[sic!] years old PR.

2026-03-04 10:03 UTC, TurnrDev commented
Thank you, sorry!

2026-03-04 10:05 UTC, TurnrDev commented
> 🍱 **[Your pull request preview is ready](https://pr-134--ideditor-presets-preview.netlify.app/id/dist/#locale=en&map=18.00/48.841708/2.587656)**
> 
> Please use this preview to check your changes. Ideally use [the **test documentation** template](https://github.com/openstreetmap/id-tagging-schema/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1&rgh-link-date=2026-03-03T00%3A50%3A22Z#L38-L69) and document your test results by commenting on the PR. This will speed up the review process for everyone.
> 
> FYI, once this PR is merged, you can use [the iD Editor Preview](http://preview.ideditor.com/) to test your changes in interaction with all other changes.

Looks to be working as intended, thanks Mr Robot!

2026-03-04 10:51 UTC, tordans commented
>Looks to be working as intended, thanks Mr Robot!

The idea is to share your testing here so we dont have to do it manually during our PR review. The minimum would be a URL to the case that shows the result in the test instance. But the test docs request more for good reason.

2026-03-04 11:27 UTC, TurnrDev commented
Sure, I'll look into it now.

2026-03-04 11:44 UTC, TurnrDev commented
## Test-Documentation

### Preview links & Sidebar Screenshots     
https://pr-134--ideditor-presets-preview.netlify.app/id/dist/#locale=en&map=19.92/52.98011/-1.15071&disable_features=boundaries&background=Bing&id=w1485346385

### Search
<img width="2809" height="1552" alt="image" src="https://github.com/user-attachments/assets/ae91d0a3-36f2-4308-97d1-49c6ebd6a56c" />

### Info-`i`

<img width="392" height="682" alt="image" src="https://github.com/user-attachments/assets/8c59602d-6429-4d5c-b812-c5a3fba574bb" />

### Wording

- [x] American English
- [x] `name`, `aliases` (if present) use Title Case
- [x] `terms` (if present) use lower case, sorted A-Z
<!-- Learn more in https://github.com/openstreetmap/id-tagging-schema/blob/main/GUIDELINES.md#2-design-the-preset -->

2026-03-04 13:42 UTC, matkoniecz commented
> Also, the playground icon is really not ideal, since the schoolyard is supposed to be a mapped alongside a school's actual playground.

hmm, maybe running person/running child icon is available?

see https://github.com/ideditor/schema-builder/blob/main/ICONS.md#icons

https://commons.wikimedia.org/wiki/Category:SVG_warning_road_signs_%E2%80%93_children has some public domain SVGs that could be extracted and added, say to Temaki (like it happened with https://github.com/rapideditor/temaki/pull/102 for #1964)

2026-03-04 13:50 UTC, matkoniecz commented
https://commons.wikimedia.org/wiki/File:141-20_Deti_(umiestnenie_v%C4%BEavo).svg has some potential for dark humour, but smaller figure may be potentially working well at scale of iD icons

if you are not interested in dealing with icon creation - maybe create an independent issue about missing icon? there is chance that someone else would be interested in it

2026-03-04 14:13 UTC, TurnrDev commented
I'll put this on my to-do

2026-03-14 00:34 UTC, andrewharvey commented on data/presets/leisure/schoolyard.json
> +        "operator",
What would be the point of `operator`? Wouldn't it almost always be the `amenity=school` that the `leisure=schoolyard` is within?

2026-04-07 14:11 UTC, TurnrDev commented
Took me a while, but I put a PR up for the icon
https://github.com/rapideditor/temaki/pull/108

2026-04-07 14:11 UTC, TurnrDev commented on data/presets/leisure/schoolyard.json
> +        "operator",
Most things seem to have this by default, I didn't much think about it.

2026-07-17 03:25 UTC, matkoniecz commented
`pinhead-person_running_after_person` icon would work, I think

https://pinhead.ink/#person_running_after_person

2026-07-17 13:59 UTC, TurnrDev commented
I've updated that now @matkoniecz

2026-07-20 17:52 UTC, matkoniecz commented
```

🏗   Validating and building dist files...

expected terms

[
  "blacktop",
  "recess yard",
  "school playground",
  "schoolyard"
]

differ from actual ones

blacktop,school playground,schoolyard,recess yard
Expected terms in preset "leisure/schoolyard" to be lowercase and sorted alphabetically.
Error: Process completed with exit code 1.

```

2026-07-20 17:53 UTC, matkoniecz commented on data/presets/leisure/schoolyard.json
> +    ],
```suggestion
    "terms": [
        "blacktop",
        "recess yard",
        "school playground",
        "schoolyard"
    ],
```

2026-07-21 09:30 UTC, matkoniecz approved these changes

2026-07-21 09:39 UTC, merged

2026-07-21 10:43 UTC, matkoniecz commented
Thanks for the PR! It is now merged (finally!) but note that before you will see it in iD few things need to happen.

iD tagging schema needs to get release (see https://github.com/openstreetmap/id-tagging-schema/releases - latest one mentioned there is just a draft). And later needs to be pulled in by iD.

Thanks again for your contribution! If you are interested in making other one it would be really welcome!

If you are looking for some easy and useful task [look here](https://github.com/openstreetmap/id-tagging-schema/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22good%20first%20issue%22).