Add capacity for childcare and kindergarten
openstreetmap/id-tagging-schema pull request #136
Opened 2021-02-21 13:40 UTC by bagage

2021-05-27 21:48 UTC, TurnrDev approved these changes

2021-11-10 15:24 UTC, mbrzakovic commented
[Wiki page](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dkindergarten) is suggesting this is a valid combination however [taginfo](https://taginfo.openstreetmap.org/tags/amenity=kindergarten#combinations) shows that kindergarten + capacity is very rarely used (same for childcare).
This seems like an item that shouldn't belong in the 'fields' but somewhere in between 'moreFields' and not including it at all as a suggestion.
@TurnrDev opinion?

2021-12-14 17:21 UTC, tyrasd requested changes
can you please include `amenity=school` here as well and move the field to the `moreFields` section?

2021-12-19 10:48 UTC, bagage commented
@tyrasd  should be good :)

2022-01-03 12:46 UTC, tyrasd approved these changes

2022-01-03 12:46 UTC, merged