Add busway preset
openstreetmap/id-tagging-schema pull request #164
Opened 2021-04-22 22:18 UTC by kolgza

Closes #163

2021-04-23 22:03 UTC, ZeLonewolf requested changes
Need to fix typos

2021-04-23 22:03 UTC, ZeLonewolf commented on data/deprecated.json
> +		"replace": {"highwat": "busway"}
Typo - should be `highway`

2021-04-23 22:03 UTC, ZeLonewolf commented on data/presets/highway/busway.json
> +        "bus radid transit",
typo - should be `bus rapid transit`

2021-04-24 16:42 UTC, kolgza commented
https://github.com/openstreetmap/id-tagging-schema/tree/main/dist/translations needs to be updated

2021-05-27 21:49 UTC, TurnrDev approved these changes

2021-11-10 16:35 UTC, mbrzakovic approved these changes

2021-11-10 16:35 UTC, mbrzakovic commented on data/presets/highway/busway.json
> +        "busway",
It would be slightly better to put these as 'aliases'. See [this](https://github.com/ideditor/schema-builder/issues/3).

2021-12-14 17:43 UTC, tyrasd commented on data/presets/highway/busway.json
> +        "emergency": "yes"
why should these tags be added, given that they are implied by the [highway=busway](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway) tag already?

2022-10-14 11:54 UTC, merged