Create shoulder.json
openstreetmap/id-tagging-schema pull request #223
Opened 2021-08-21 07:18 UTC by ZEE6de

{
    "key": "shoulder",
    "type": "check",
    "label": "Shoulder",
}

2021-08-21 07:19 UTC, ZEE6de commented
https://wiki.openstreetmap.org/wiki/Key:shoulder

2021-10-20 06:11 UTC, matkoniecz requested changes

2021-10-20 06:11 UTC, matkoniecz commented on shoulder.json
> +
This creates an empty file, is it intentional and sufficient?

2021-12-13 18:02 UTC, tyrasd requested changes
please fix the error pointed out by @matkoniecz above and please also change the highway presets directly in this pull request.

2022-01-22 12:08 UTC, closed without merging