added highway=emergency_access_point
openstreetmap/id-tagging-schema pull request #504
Opened 2022-06-17 20:13 UTC by tiptoptom

I tried to make a PR for highway=emergency_access_point. This is my first PR here so I hope, everything is fine. And if not forgive me =)

#20

2022-06-20 10:21 UTC, tyrasd requested changes
Hi. Thanks for your pull request. It definitely makes sense to include a preset for this feature. :+1: 

See the comments below for a few tweaks to be made before the preset can be merged into the index.

2022-06-20 22:12 UTC, tiptoptom commented on data/presets/highway/emergency_access_point.json
> +    "name": "Highway Emergency Access Point"
But for hiking trails etc. I think emergency=access_point is more intended. highway=emergency_access_point refers I think from the tag to a road.

2022-06-21 07:39 UTC, tyrasd commented on data/presets/highway/emergency_access_point.json
> +    "name": "Highway Emergency Access Point"
Hm… the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Demergency_access_point) doesn't mention that `highway=emergency_access_point` is limited to roadside rescue points. On the contrary, it seems to indicate that off-road rescue points are the main intended purpose behind the tag:

> For areas which are hard to access, like woods or waterways, some countries offer a network of emergency access points.

Also, most examples I could find are along hiking paths, see https://overpass-turbo.eu/s/1jv1 to check yourself.

2022-06-21 10:28 UTC, tiptoptom commented on data/presets/highway/emergency_access_point.json
> +    "name": "Highway Emergency Access Point"
Ok, you may be right. I just wanted to create a demarcation to emergency=access_point …
But that doesn't have to be right now.

2022-06-21 12:30 UTC, tyrasd approved these changes

2022-06-21 12:30 UTC, merged