Add a field for the key "model"
openstreetmap/id-tagging-schema pull request #584
Opened 2022-09-19 14:06 UTC by Lukas458

Hi,
the key "model" ( https://wiki.openstreetmap.org/wiki/Key%3Amodel ) describes the model designation of a manufactured object. Formerly, it has been used for power=generator mainly, but now its usage has increased and is spread around over vrious objects which can have a model-designation / model-name. For example public telephones, elevators, street cabinets, substations and so on. **It is used over 32000 times.** So I think it's worth adding it. The kind of field should be free-text generally, but I chose the field type "combo" so that people can orientate on which values are already in use. For this, there's also the case-sensivity important.

2022-09-20 11:45 UTC, tyrasd requested changes
This PR is missing the inclusion of the new field in the respective presets. Can you add it add it at least to the `street_cabinet` preset and any other presets where you think it should be included, please?

It' s unfortunate that for find turbines, the `manufacturer:type` tag is used more frequently than the `model` tag. But there is a [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Manufacturer_and_Model) on the way to deprecate that tag in favor of `model`, so I think it is reasonable to only support `model` in iD for now.

2022-09-21 07:21 UTC, Lukas458 commented
> This PR is missing the inclusion of the new field in the respective presets. Can you add it add it as an optional field (moreFields) at least to the street_cabinet preset and any other presets where you think it should be included, please?

Oh sorry, I wrongly thought that the new-field.json needed to come first and this work needs to come after then. Of course I can add it to some presets, I will do that then.

> It' s unfortunate that for find turbines, the manufacturer:type tag is used more frequently than the model tag.

Oh yes, I see, another case where for some single main-tag a special under-tag had been created/used. I share your opinion that `model` is in fact more useful in that it can be used independently for a breadth/abundance of objects while being independent from any other tags.

2022-09-23 09:00 UTC, tyrasd approved these changes

2022-09-23 09:01 UTC, merged

2022-09-23 09:02 UTC, tyrasd commented
merged, thanks!