Add common independent physicians
openstreetmap/id-tagging-schema pull request #718
Opened 2022-12-26 17:37 UTC by westnordost

Adds commons independent physicians as selectable presets.

2022-12-28 20:12 UTC, arch0345 requested changes
`terms` are typically all lowercase while `names` and `aliases` are typically in title case

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/general.json
> +        "General practitioner"
```suggestion
    "name": "Primary Care Physician",
    "aliases": [
        "General Practitioner"
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/general.json
> +        "Family Doctor"
```suggestion
        "gp",
        "family physician",
        "family practitioner",
        "family doctor"
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/orthopaedics.json
> +        "Orthopedic surgery"
```suggestion
        "orthopedic surgery"
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/otolaryngology.json
> +        "Otorhinolaryngology",
```suggestion
        "ent",
        "head and neck surgery",
        "nose",
        "ohns",
        "orl",
        "orl–h&n",
        "otolaryngologist",
        "otorhinolaryngology",
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/paediatrics.json
> +        "Paediatrics"
```suggestion
        "paediatrics"
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/pathology.json
> +        "Anatomic pathology",
```suggestion
        "anatomical pathology",
        "anatomic pathology",
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/proctology.json
> +        "Proctology"
```suggestion
        "colorectal surgery",
        "proctology"
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/surgery.json
> +    "name": "General surgeon"
```suggestion
    "name": "General Surgeon"
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/trauma.json
> +        "Trauma surgery"
```suggestion
        "surgery",
        "trauma surgery"
```

2022-12-28 20:12 UTC, arch0345 commented on data/presets/amenity/doctors/rheumatology.json
> +        "Rheumatology"
```suggestion
        "rheumatology"
```

2023-01-09 16:59 UTC, tyrasd commented
Merged as d40b047, as there was a small mistake in these presets: `addTags` needs to repeat the main tags of a preset in most cases. See https://github.com/ideditor/schema-builder#addtags

2023-01-09 16:59 UTC, closed without merging

2023-01-09 22:20 UTC, westnordost commented
Oh, I see. Thank you.