Update birthing_centre.json, add doctors-PH.json
openstreetmap/id-tagging-schema pull request #958
Opened 2023-07-13 00:05 UTC by govvin

Added additional terms for healthcare=birthing_centre preset. Fix typo.

Add regional variant for doctors-PH.json, including aliases.

2023-07-18 11:54 UTC, tyrasd requested changes
:+1: for the changes to the Birthing Center preset

But regarding the Doctor preset: Am I seeing it correctly that the only change is the country-specific `aliases`? I would have said that such aliases could be easier managed through a translation on transifex: I've just opened translation for `en_PH` _English (Philippines)_ for this: https://app.transifex.com/openstreetmap/id-editor/translate/#en_PH/presets/68222339?q=key%3Adoctors. Does that make sense here?

2023-07-18 11:54 UTC, tyrasd commented on data/presets/healthcare/birthing_center.json
> +    },
```suggestion
    "addTags": {
        "healthcare": "birthing_centre",
        "healthcare:speciality": "maternity"
    },
```

2023-07-18 22:52 UTC, govvin commented
Thanks for reviewing this @tyrasd .

As for the doctors-PH.json, I'm not really sure if translation if the way to go. 

The "RHU"/Rural Health Unit is a local type of field health facility operated by a government, under the supervision of a government physician, which (locally) may be then tagged as amenity=doctor/healthcare=doctor,  and similar to a doctor's office.

I wonder if it's appropriate to create a different preset to display it with a different name, rather than using translate.

2025-12-16 13:54 UTC, matkoniecz commented on data/presets/amenity/doctors-PH.json
> +        "Rural Health Unit",
so these are PH-specific names for `amenity=doctors` - without any special tagging?

2025-12-16 23:00 UTC, govvin commented on data/presets/amenity/doctors-PH.json
> +        "Rural Health Unit",
It's a common health service provided by the government in rural areas, often GPs.  I'd say it's alright to add the `healthcare:speciality=general;community`

2026-03-01 12:55 UTC, matkoniecz commented on data/presets/amenity/doctors-PH.json
> +        "Rural Health Unit",
If "Rural Health Unit" makes sense as dedicated entry with own tags then they should be own preset entries.

I am still unsure why dedicated PH entry is created here - is it to add this extra terms?

2026-03-01 12:56 UTC, matkoniecz commented on data/presets/healthcare/birthing_center.json
> +        "healthcare:speciality": "maternity"
if `"healthcare:speciality": "maternity"` should be mass added to all `healthcare=birthing_centre` (seems pointless to me) then it should be done as an approved bot edit, see https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct

2026-03-01 12:56 UTC, matkoniecz commented on data/presets/healthcare/birthing_center.json
> +        "midwife",
are there other objects that should appear when one search with midwife/maternity term?

2026-03-01 12:57 UTC, matkoniecz commented on data/presets/healthcare/birthing_center.json
> +        "lying-in",
https://en.wikipedia.org/wiki/Lying-in - I guess that it may be reasonable search term?

2026-08-26 23:52 UTC, matkoniecz commented on data/presets/healthcare/birthing_center.json
> +        "healthcare:speciality": "maternity"
@govvin ping?

2026-08-26 23:55 UTC, matkoniecz commented on data/presets/amenity/doctors-PH.json
> +        "Rural Health Unit",
@govvin

2026-08-27 00:53 UTC, govvin commented on data/presets/healthcare/birthing_center.json
> +        "healthcare:speciality": "maternity"
That’s a good point! I don’t think it’s necessary, and can just leave the primary tag there. 

I'll drop it from the PR.

2026-09-05 04:41 UTC, closed without merging